version: 0.2.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
after_build:
- 7z a ISDeploymentCmd.zip %APPVEYOR_BUILD_FOLDER%\ISDeploymentCmd\bin\%CONFIGURATION%\*.exe
artifacts:
- path: ISDeploymentCmd.zip
  name: ISDeploymentCmd
deploy
  - provider: GitHub
    artifact: ISDeploymentCmd
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true
