version: 0.1.{build}
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
after_build:
- 7z a ISDeploymentCmd.zip %APPVEYOR_BUILD_FOLDER%\bin\$(configuration)\*.exe
artifacts:
- path: ISDeploymentCmd.zip
  name: ISDeploymentCmd
